#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: .\var\log\tomcat
#  file: .\var\log\tomcat\sell.log
#  level:
#    com.imooc.sell: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.28.188:3306/sell?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell
